### PR TITLE
f24 alpha wallpapers pack

### PR DESCRIPTION
**Pull request by mashaleonova**
Here are the 4 alpha wallpapers

### CODE REVIEW

**Comment by luyatshimbalanga** [comment]
Hi Mariia. Will it be possible to make a variation version with a rotated constellation? That method was done on Fedora 20.

**Comment by luyatshimbalanga** [comment]
Also have you the source file in either svg or xcf? Thanks.

**Comment by mashaleonova** [comment]
Hi Luya!

Not sure what you mean by 'rotated constellation', checking out f20 artwork
didn't help. Can you please be more specific?
Of course I have the source file. I'm assuming the biggest one will do?
https://www.dropbox.com/s/on7mi3fzphpr9pk/f24_standard.tar.gz?dl=0

Have a nice day!

Maria

Best regards,
Maria Leonova

https://www.behance.net/masha_latte

**Comment by luyatshimbalanga** [comment]
Thanks Maria.

I made some modifications on the source file by rotating the stars as illustrated on each image. Due to the size of the source, I compressed in tar.xz for space.

https://www.dropbox.com/sh/qyu2bkuvdl7c0h1/AAAgVxK5EmTLtaI4sJfJFlsEa?dl=0

**Pull request merged**
